ndr_webui/views/organizations.py
# Copyright (C) 2017  Secured By THEM
# Original Author: Michael Casadevall <michaelc@them.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

'''Main View for Organization Index'''

import ndr_webui

import flask
from flask import render_template
from flask_login import login_required

from flask import current_app

organizations_page = flask.Blueprint('organizations', __name__,
                                     template_folder='templates')


@organizations_page.route('/')
@organizations_page.route('/organizations')
@login_required
def index():
    '''Displays the master list of organizations'''
    vcv = ndr_webui.config.get_common_variables()

    org_list = vcv.user.get_organizations_for_user(db_conn=vcv.db_conn)
    page_title = ndr_webui.config.site_name() + " - Organizations"

    return render_template('organizations.html',
                           title=page_title,
                           vcv=vcv,
                           organizations=org_list)


@organizations_page.route('/organization/<org_id>')
@login_required
def overview(org_id):
    '''Displays more in-depth information for an organization'''
    # Make sure our input parameters are sane
    org_id = int(org_id)

    vcv = ndr_webui.config.get_common_variables()

    # Grab the organization via the ACL
    org = ndr_webui.OrganizationACL.read_by_id(
        vcv.nsc, vcv.user, org_id, vcv.db_conn)

    # Now grab the list of sites, and then amend the title
    sites = vcv.user.get_sites_in_organization_for_user(org, vcv.db_conn)
    page_title = ndr_webui.config.site_name() + " - Sites - " + org.name

    return render_template('sites.html',
                           title=page_title,
                           vcv=vcv,
                           org=org,
                           sites=sites)

ndr_webui/views/site_info.py
# Copyright (C) 2017  Secured By THEM
# Original Author: Michael Casadevall <michaelc@them.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

'''Main View for Site Overview Index'''

import ndr_webui

import flask
from flask import render_template
from flask_login import login_required

from flask import current_app

site_info = flask.Blueprint('site_info', __name__,
                            template_folder='templates')

# Site Overview
@site_info.route('/site/<site_id>')
@login_required
def overview(site_id):
    '''Renders an overview of the site'''

    # Make sure our input parameters are sane
    site_id = int(site_id)

    vcv = ndr_webui.config.get_common_variables()

    # Load in the site
    site = ndr_webui.SiteACL.read_by_id(
        vcv.nsc, vcv.user, site_id, vcv.db_conn
    )

    # We need to pull the rest of the information based off the in the database

    recorders = vcv.user.get_recorders_in_site_for_user(
        site, vcv.db_conn
    )

    page_title = ndr_webui.config.site_name() + " - Sites Overview For " + site.name

    return render_template('site_overview.html',
                           title=page_title,
                           site_id=site_id,
                           recorders=recorders,
                           active_page='overview')

ndr_webui/templates/snippet/alerts_table.html
<div class="col-sm-6">
    <h2>Alerts And Notifications</h2>
    <div class="table-responsive">
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>Type</th>
                    <th>Raised</th>
                </tr>
                <tbody>
                    <tr>
                        <td>SNORT Notification</td>
                        <td>Today</td>
                    </tr>
        </table>
        </thead>
        </table>
    </div>
</div>

ndr_webui/templates/snippet/breadcrumb.html
<!-- breadcrumb element - use in mainpage div -->
<div class="row">
    <ul class="breadcrumb">
        <li><a href="#">Home</a></li>
        <li><a href="#">Products</a></li>
        <li class="active">Accessories</li>
    </ul>
</div>

ndr_webui/templates/snippet/flashes.html
<div class="row">
{% with messages = get_flashed_messages(with_categories=true) %}
  {% if messages %}
    {% for category, message in messages %}
      <div class="alert alert-{{category}} alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          {{message}}
      </div>
    {% endfor %}
    </ul>
  {% endif %}
{% endwith %}
</div>

ndr_webui/templates/snippet/nmap_recent_scans.html
<!-- nmap block -->
<div class="col-sm-6">
    <h2>NMAP System Scan Results</h2>
    <div class="table-responsive">
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>IP Address</th>
                    <th>MAC Address</th>
                    <th>Operating System</th>
                    <th>Classification</th>
                    <th>Last Seen</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>
                        192.168.2.2
                    </td>
                    <td>AA:BB:CC:DD:EE:FF</td>
                    <td>Linux 3.x</td>
                    <td>Desktop</td>
                    <td>Now</td>
                </tr>
                <tr>
                    <td>
                        192.168.2.2
                    </td>
                    <td>AA:BB:CC:DD:EE:FF</td>
                    <td>Linux 3.x</td>
                    <td>Desktop</td>
                    <td>Now</td>
                </tr>
            </tbody>
        </table>
    </div>
</div>

ndr_webui/templates/snippet/org_table.html
<div class="table-responsive">
    <table class="table table-striped">
        <thead>
            <tr>
                <th>Organization</th>
            </tr>
        </thead>
        <tbody>
            {% for org in organizations %}
            <tr>
                <td><a href="{{ url_for('organizations.overview', org_id=org.pg_id) }}">
                {{org.name}}
                </a>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>

ndr_webui/templates/snippet/recorder_table.html
<div class="row">
    <h2>Recorders In Site</h2>
    <div class="table-responsive">
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Hostname</th>
                    <th>Software Revision</th>
                    <th>Hardware Revision</th>
                    <th>Last Seen</th>
                    <th>Uptime</th>
                </tr>
                <tbody>
                    {% for recorder in recorders %}
                    <tr>
                        <td>{{ recorder.human_name }}</td>
                        <td>{{ recorder.hostname }}</td>
                        <td>Unknown</td>
                        <td>Unknown</td>
                        <td>Unknown</td>
                        <td>Unknown</td>
                    </tr>
                    {% endfor %}
        </table>
        </thead>
    </div>
</div>

ndr_webui/templates/snippet/site_stats_table.html
<div class="col-sm-6">
    <h2>Site Stats</h2>
    <div class="table-responsive">
        <table class="table table-striped">
            <tbody>
                <tr>
                    <td>Machines Seen</td>
                    <td>10</td>
                </tr>
                <tr>
                    <td>Messages Logged</td>
                    <td>9000</td>
                </tr>
                <tr>
                    <td>Outbound Traffic</td>
                    <td>812 Mib</td>
                </tr>
                <tr>
                    <td>Inbound Traffic</td>
                    <td>10 GiB</td>
                </tr>
        </table>
    </div>
</div>

ndr_webui/templates/snippet/site_table.html
<div class="table-responsive">
    <table class="table table-striped">
        <thead>
            <tr>
                <th>Sites</th>
            </tr>
        </thead>
        <tbody>
            {% for site in sites %}
            <tr>
                <td><a href="{{ url_for('site_info.overview', site_id=site.pg_id) }}">
                {{site.name}}
                </a>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>

ndr_webui/templates/snippet/syslogs_table.html
<!-- syslog block -->
<div class="col-sm-6">
    <h2>High-Priority Syslog Entries</h2>
    <div class="table-responsive">
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>Timestamp</th>
                    <th>Program</th>
                    <th>Priority</th>
                    <th>Host</th>
                    <th>Message</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>1,001</td>
                    <td>Lorem</td>
                    <td>ipsum</td>
                    <td>dolor</td>
                    <td>sit</td>
                </tr>
                <tr>
                    <td>1,002</td>
                    <td>amet</td>
                    <td>consectetur</td>
                    <td>adipiscing</td>
                    <td>elit</td>
                </tr>
                <tr>
                    <td>1,003</td>
                    <td>Integer</td>
                    <td>nec</td>
                    <td>odio</td>
                    <td>Praesent</td>
                </tr>
                <tr>
                    <td>1,003</td>
                    <td>libero</td>
                    <td>Sed</td>
                    <td>cursus</td>
                    <td>ante</td>
                </tr>
                <tr>
                    <td>1,004</td>
                    <td>dapibus</td>
                    <td>diam</td>
                    <td>Sed</td>
                    <td>nisi</td>
                </tr>
                <tr>
                    <td>1,005</td>
                    <td>Nulla</td>
                    <td>quis</td>
                    <td>sem</td>
                    <td>at</td>
                </tr>
                <tr>
                    <td>1,006</td>
                    <td>nibh</td>
                    <td>elementum</td>
                    <td>imperdiet</td>
                    <td>Duis</td>
                </tr>
                <tr>
                    <td>1,007</td>
                    <td>sagittis</td>
                    <td>ipsum</td>
                    <td>Praesent</td>
                    <td>mauris</td>
                </tr>
                <tr>
                    <td>1,008</td>
                    <td>Fusce</td>
                    <td>nec</td>
                    <td>tellus</td>
                    <td>sed</td>
                </tr>
            </tbody>
        </table>
    </div>
</div>